build(generator): Add experimental custom fastapi-code-generator.
ExpediaGroup/openworld-sdk-python pull request #39
Opened 2023-02-12 18:26 UTC by OmarAlJarrah

### :pencil: Description
- 

### :link: Related Issues
-

2023-02-12 20:48 UTC, OmarAlJarrah commented
Wherever there is a change I made, and the code is not identical to the original code in fastapi-code-generator, a comment have been added to mark the change and give it a description.

All comments follow the pattern `# openworld: <description>.`

2023-02-13 14:42 UTC, mohnoor94 requested changes

2023-02-14 14:00 UTC, OmarAlJarrah commented on openworld/sdk/generator/client/__main__.py
> +    # openworld: set new visitors path.
Discussed offline

2023-02-14 15:35 UTC, mohnoor94 approved these changes

2023-02-15 10:59 UTC, merged